
services:
  fly-cli-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fly-cli-app
    ports:
      - "${FLY_CLI_PORT_HOST:-5010}:${FLY_CLI_PORT_CONTAINER:-5005}"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
      - ENABLE_COMMAND_MANAGEMENT=true
      - ENABLE_FILE_MANAGEMENT=false
      - ENABLE_SERVER_MANAGEMENT=false
    volumes:
      - ~/.fly/config.yml:/root/.fly/config.yml:rw # `fly login` to initially generate config.yml
    restart: unless-stopped