
services:
  fly-cli-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fly-cli-app
    ports:
      - "${FLY_CLI_PORT_HOST:-5010}:${FLY_CLI_PORT_CONTAINER:-5005}"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
    volumes:
      - ~/.fly:/root/.fly:rw
    restart: unless-stopped