version: '3.8'

services:
  vercel-cli-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vercel-cli-app
    ports:
      - "${VERCEL_CLI_PORT_HOST:-5002}:${VERCEL_CLI_PORT_CONTAINER:-5005}"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
      - VERCEL_AUTH_TOKEN=${VERCEL_AUTH_TOKEN}
    restart: unless-stopped
    volumes:
      - ./config:/app/config:ro # Read-only if needed
