# docker/netlify-cli/docker-compose.yml

version: '3.8'

services:
  netlify-cli-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netlify-cli-app
    ports:
      - "${NETLIFY_CLI_PORT_HOST:-5001}:${NETLIFY_CLI_PORT_CONTAINER:-5005}"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
      - NETLIFY_AUTH_TOKEN=${NETLIFY_AUTH_TOKEN}
    restart: unless-stopped
    volumes:
      - ./config:/app/config:ro # Read-only if needed
