app = "gpt-terminal-plus"
primary_region = "syd"

[build]
  dockerfile = "../docker/gpt-terminal-plus/Dockerfile"

[env]
  PORT = "5004"
  NODE_ENV = "production"
  NODE_CONFIG_DIR = "/data/config"

[http_service]
  internal_port = 5004
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "20s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
  swap_size_mb = 1024

[[mounts]]
source = "mydata1"
destination = "/data"
