# fly.toml app configuration file generated for gpt-aws-cli on 2024-07-30T21:16:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gpt-aws-cli'
primary_region = 'syd'

[build]
  dockerfile = 'docker/Dockerfile.aws'

[env]
  NODE_CONFIG_DIR = '/data/config'
  NODE_ENV = 'production'
  PORT = '5004'

[[mounts]]
  source = 'mydata2'
  destination = '/data'

[http_service]
  internal_port = 5004
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
