# fly.toml app configuration file generated for gpt-terminal-plus on 2024-08-05T05:40:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gpt-terminal-plus'
primary_region = 'syd'

[build]
  image = 'mhand79/gpt-terminal-plus'

[env]
  NODE_CONFIG_DIR = '/data/config'
  NODE_ENV = 'production'
  PORT = '5005'

[[mounts]]
  source = 'mydata1'
  destination = '/data'

[http_service]
  internal_port = 5005
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
