version: "3.8"

services:
  gcloud-cli-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gcloud-cli-app
    ports:
      - "${GCLOUD_CLI_PORT_HOST:-5007}:${GCLOUD_CLI_PORT_CONTAINER:-5005}"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
      - GCLOUD_PROJECT=${GCLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud:ro
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    restart: unless-stopped

volumes:
  gcloud-config: