version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5004" # Map the port from your container to the host
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
      - NOTION_TOKEN=${NOTION_TOKEN}
      - OCI_COMPARTMENT_ID=${OCI_COMPARTMENT_ID}
      - OCI_COMPARTMENT_NAME=${OCI_COMPARTMENT_NAME}
    volumes:
      - /usr/src/app/node_modules # Keep node_modules on a named volume
      - ../.aws:/root/.aws:ro # Mount the AWS configuration directory
      - ../.ssh:/root/.ssh:rw # Mount the SSH directory (rw required for updating host keys)
      - /etc/hosts:/etc/hosts:ro  # for name resolution
      - /home/chatgpt/bin:/home/chatgpt/bin # for `oci` binary
      - /home/chatgpt/lib:/home/chatgpt/lib # for `oci` binary
      - /mnt/models/lib/oracle-cli:/opt/oracle-cli
      - /home/chatgpt/.oci:/home/chatgpt/.oci:ro # need full path because oci installation hardcodes it
    restart: unless-stopped
