app = "gpt-terminal-plus"
primary_region = "syd"

[build]
  dockerfile = "docker/Dockerfile.gpt-terminal-plus"

[env]
  PORT = "5004"
  # NEVER SET NODE_ENV = "production" (wont compile index.js)
  NODE_ENV = "development"
  NODE_CONFIG_DIR = "/data/config"

[http_service]
  internal_port = 5004
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  internal_port = 5004
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "10s"
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "5s"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
  swap_size_mb = 1024

[[mounts]]
source = "mydata1"
destination = "/data"
