services:
  gpt-terminal-plus-pb:
    image: mhand79/gpt-terminal-plus:latest
    env_file:
      - .env
    ports:
      - "5001:5005"
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - ENABLE_COMMAND_MANAGEMENT=true
      - ENABLE_FILE_MANAGEMENT=false
      - ENABLE_SERVER_MANAGEMENT=true
      - NODE_ENV=development # Needed for multi-stage ie installs compiler `tsc`
    volumes:
      - ~/.aws:/root/.aws:ro
      - ~/.ssh:/root/.ssh:rw
    restart: unless-stopped
