FROM common-base-image AS builder

WORKDIR /app

# Install Node.js dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Install Python boto3
RUN pip3 install boto3

COPY . .

RUN npm run build

FROM common-base-image

WORKDIR /app

COPY --from=builder /app .

CMD ["node", "dist/index.js"]