# Use common base image
FROM common-base-image

# Set the working directory
WORKDIR /root

# Install OCI CLI
RUN apt-get update \
    && apt-get install -y curl \
    && bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" --accept-all-defaults \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Command to run the OCI CLI
CMD ["oci"]
