FROM common-base-image AS builder

WORKDIR /app

# Install Joplin CLI
RUN npm install -g joplin

COPY . .

RUN npm run build

FROM common-base-image

WORKDIR /app

COPY --from=builder /app .

CMD ["joplin"]