# Dockerfile for aws-cli
# Base image is common-base-image

# Use common-base-image as the base image
FROM common-base-image

# Install aws-cli and the aws-sdk-js
RUN apt-get update \
    && apt-get install -y awscli \
    && npm install aws-sdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create and set the working directory
WORKDIR /root

# Specify the volume for AWS credentials
# ~/.aws/ is used for AWS credentials etc
VOLUME ["/root/.aws"]

# Entry point for the container
ENTRYPOINT ["/bin/bash"]
