# ================================
# Stage 1: Build the application
# ================================
# Use the common base image for the build stage
FROM common-base-image AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install Node.js dependencies, allowing for legacy peer dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code to the working directory
COPY . .

# Build the application
RUN npm run build

# ================================
# Stage 2: Create the production image
# ================================
# Use the common base image for the production stage
FROM common-base-image

# Set the working directory inside the container
WORKDIR /app

# Copy built files from the builder stage to the working directory
COPY --from=builder /app .

# Define the command to run the application
CMD ["node", "dist/index.js"]