FROM common-base-image AS builder

WORKDIR /app

# Install any additional dependencies if needed
COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

FROM common-base-image

WORKDIR /app

COPY --from=builder /app .

CMD ["node", "dist/index.js"]