FROM common-base-image AS builder

WORKDIR /app

COPY package*.json ./

# Install Node.js dependencies and the Notion SDK client
RUN npm install --legacy-peer-deps @notionhq/client

COPY . .

RUN npm run build

FROM common-base-image

WORKDIR /app

COPY --from=builder /app .

CMD ["node", "dist/index.js"]