services:
  gpt-terminal-plus-pb:
    image: mhand79/gpt-terminal-plus:latest
    env_file:
      - .env
    ports:
      - "5002:5005"
    environment:
      - NODE_ENV=development # Needed for multi-stage ie installs compiler `tsc`
    restart: unless-stopped
