version: '3.8'
services:
  flowise-sdk:
    build: .
    environment:
      # API token for authentication, required to access Flowise
      - API_TOKEN=${API_TOKEN}
      # Flowise API key to interact with the service
      - FLOWISE_API_KEY=${FLOWISE_API_KEY}
      # Base URL for the Flowise service
      - FLOWISE_URL=${FLOWISE_URL}
    # Expose the service on port 5019 for the host, 5005 inside the container
    ports:
      - "${FLOWISE_PORT_HOST:-5019}:${FLOWISE_PORT_CONTAINER:-5005}"
    # Automatically restart the service unless manually stopped
    restart: unless-stopped
    # Mount the local scripts directory to allow custom shell functions
    volumes:
      - ./scripts/:/scripts:rw
