services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oci-cli-app
    ports:
      - "${OCI_CLI_PORT_HOST:-5006}:${OCI_CLI_PORT_CONTAINER:-5005}"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
      - OCI_COMPARTMENT_ID=${OCI_COMPARTMENT_ID}
      - OCI_COMPARTMENT_NAME=${OCI_COMPARTMENT_NAME}
      - ENABLE_COMMAND_MANAGEMENT=true
      - ENABLE_FILE_MANAGEMENT=false
      - ENABLE_SERVER_MANAGEMENT=false
    volumes:
      - ~/.oci:/root/.oci:ro
    restart: unless-stopped
