services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monday-cli-app
    ports:
      - "${MONDAY_SDK_PORT_HOST:-5017}:${MONDAY_SDK_PORT_CONTAINER:-5005}"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
      - MONDAY_TOKEN=${MONDAY_TOKEN}
      - ENABLE_COMMAND_MANAGEMENT=true
      - ENABLE_FILE_MANAGEMENT=true
      - ENABLE_SERVER_MANAGEMENT=false
    restart: unless-stopped
    volumes:
      - ./scripts/:/scripts:rw # for storing shell functions to be loaded on each session
      - .bashrc:/root/.bashrc # for disabling various expansions
