FROM mhand79/gpt-terminal-plus:latest

WORKDIR /app

# Install monday sdk for JS
RUN npm install monday-sdk-js

# Install monday-cli
#RUN npm install -g @mondaycom/apps-cli
#RUN mapps init -t ${MONDAY_TOKEN}

# CMD ["node", "dist/index.js"] inherited from Dockerfile.base
