{
  boards(ids: 2809374317) {
    groups(ids: "new_group81872") {
      items_page(limit: 10) {
        items {
          id
          name
          column_values(ids: "genre6__1") {
            id
            text
          }
        }
      }
    }
  }
}
