version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.terminal
    ports:
      - "5005:5004"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
    volumes:
      - ../.ssh:/root/.ssh:rw
    restart: unless-stopped
