services:
  terminal:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.terminal
    ports:
      - "5005:5004"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
    volumes:
      - ../.ssh:/root/.ssh:rw
    restart: unless-stopped

  oci:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.oci
    ports:
      - "5006:5004"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
      - OCI_COMPARTMENT_ID=${OCI_COMPARTMENT_ID}
      - OCI_COMPARTMENT_NAME=${OCI_COMPARTMENT_NAME}
    volumes:
      - /mnt/models/lib/oracle-cli:/opt/oracle-cli
    restart: unless-stopped

  aws:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.aws
    ports:
      - "5007:5004"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    volumes:
      - ../.aws:/root/.aws:ro
    restart: unless-stopped

  notions:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.notions
    ports:
      - "5008:5004"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
      - NOTION_TOKEN=${NOTION_TOKEN}
    restart: unless-stopped

  joplin:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.joplin
    ports:
      - "5009:5004"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
    restart: unless-stopped
