services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.oci
    ports:
      - "5006:5004"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
      - OCI_COMPARTMENT_ID=${OCI_COMPARTMENT_ID}
      - OCI_COMPARTMENT_NAME=${OCI_COMPARTMENT_NAME}
    volumes:
      - /mnt/models/lib/oracle-cli:/opt/oracle-cli
    restart: unless-stopped
