version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.aws
    ports:
      - "5007:5004"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
    volumes:
      - ../.aws:/root/.aws:ro
    restart: unless-stopped
