services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.oci-cli
    image: oci-cli-app
    container_name: oci-cli-app
    ports:
      - "5006:5004"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
      - OCI_COMPARTMENT_ID=${OCI_COMPARTMENT_ID}
      - OCI_COMPARTMENT_NAME=${OCI_COMPARTMENT_NAME}
    volumes:
      - ~/.oci:/root/.oci:ro
    restart: unless-stopped