services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.aws
    image: aws:latest
    depends_on:
      - base
    ports:
      - "5007:5004"
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    volumes:
      - ../.aws:/root/.aws:ro
    restart: unless-stopped
