services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: joplin-app
    ports:
      - "${JOPLIN_PORT_HOST:-5009}:${JOPLIN_PORT_CONTAINER:-5004}"
    env_file:
      - ../../../.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
      - API_TOKEN=${API_TOKEN}
    restart: unless-stopped
