name: Deploy AWS CLI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Fly.io Docker registry
      run: echo "${{ secrets.FLY_API_TOKEN }}" | docker login registry.fly.io -u _json_key --password-stdin

    - name: Pull Docker image
      run: docker pull registry.fly.io/gpt-terminal-plus:latest

    - name: Deploy to Fly.io
      run: |
        curl -L https://fly.io/install.sh | sh
        flyctl auth token
        flyctl deploy --image registry.fly.io/gpt-terminal-plus:latest
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}