name: Deploy AWS CLI

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_IO_USERNAME }}
        password: ${{ secrets.DOCKER_IO_AUTH }}

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_IO_USERNAME }}/gpt-terminal-plus:latest

    - name: Deploy to Fly.io
      run: |
        curl -L https://fly.io/install.sh | sh
        flyctl auth token
        flyctl deploy --config fly_configs/fly-terminal-app.toml --image ${{ secrets.DOCKER_IO_USERNAME }}/gpt-terminal-plus:latest
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}