name: Deploy AWS CLI App to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build and push Docker image
        run: |
          docker build -f docker/Dockerfile.aws -t docker_image_aws .
          docker tag docker_image_aws registry.fly.io/app_aws:latest
          docker push registry.fly.io/app_aws:latest

      - name: Deploy to Fly.io
        run: flyctl deploy -c fly_configs/fly-aws-app.toml --image registry.fly.io/app_aws:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
