name: Deploy AWS CLI App to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy -c fly_configs/fly-aws-app.toml --wait-timeout 300
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
