name: Build and Deploy Terminal

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Fly.io Docker registry
      run: echo "${{ secrets.FLY_DOCKER_REGISTRY_AUTH }}" | base64 --decode | docker login registry.fly.io -u _json_key --password-stdin

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: registry.fly.io/gpt-terminal-plus:latest

    - name: Deploy to Fly.io
      run: |
        curl -L https://fly.io/install.sh | sh
        flyctl auth token
        flyctl deploy --config fly_configs/fly-terminal-app.toml --image registry.fly.io/gpt-terminal-plus:latest
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}